import React from 'react';
import { AnalysisResult } from '../types';
import { Button } from './Button';
import { Download, Share2, RefreshCw, Users, Briefcase, Flag, Utensils } from 'lucide-react';

interface ResultScreenProps {
  result: AnalysisResult;
  imageUrl: string | null;
  foodImageUrl: string | null;
  onReset: () => void;
  userName: string;
}

export const ResultScreen: React.FC<ResultScreenProps> = ({ result, imageUrl, foodImageUrl, onReset, userName }) => {
  
  const handleDownload = () => {
    const element = document.createElement("a");
    const careerText = result.careerPath
      .map(c => `* ${c.role}: ${c.reason}`)
      .join('\n');

    const reportText = `
PSYCHOCINEMATCH REPORT
----------------------
Subject: ${userName}
Subject Match: ${result.characterName} (${result.movieTitle})
Personality Type: ${result.personalityType}

FOOD SOULMATE:
Dish: ${result.foodMatch}
Why: ${result.foodReason}

SUGGESTED CAREER PATHS:
${careerText}

GREEN FLAGS (STRENGTHS):
${result.greenFlags.map(s => `- ${s}`).join('\n')}

RED FLAGS (WEAKNESSES):
${result.redFlags.map(w => `- ${w}`).join('\n')}

DETAILED PSYCHOLOGICAL ANALYSIS:
${result.detailedReport}

Generated by PsychoCineMatch AI
    `;
    const file = new Blob([reportText], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `PsychProfile_${userName.replace(/\s+/g, '_')}_${result.characterName.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleShare = async () => {
    const text = `I matched with ${result.characterName} from ${result.movieTitle} on PsychoCineMatch! My food soulmate is ${result.foodMatch}. #PsychoCineMatch`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${userName}'s Psychological Profile`,
          text: text,
          url: window.location.href
        });
      } catch (err) {
        console.error('Share failed', err);
      }
    } else {
      await navigator.clipboard.writeText(text);
      alert("Result copied to clipboard!");
    }
  };

  return (
    <div className="max-w-5xl mx-auto p-4 md:p-8 fade-in pb-20">
      <div className="grid md:grid-cols-2 gap-12 items-start">
        
        {/* Left Column: Image & Identity */}
        <div className="space-y-6 sticky top-8">
          <div className="relative group rounded-2xl overflow-hidden shadow-2xl shadow-black/50 border border-dark-700">
            {imageUrl ? (
              <img 
                src={imageUrl} 
                alt={result.characterName} 
                className="w-full h-auto object-cover transform transition-transform duration-700 group-hover:scale-110"
              />
            ) : (
              <div className="w-full h-96 bg-dark-800 flex items-center justify-center text-gray-500">
                Image Generation Failed
              </div>
            )}
            <div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent opacity-80"></div>
            <div className="absolute bottom-0 left-0 p-6">
              <p className="text-accent-400 font-bold uppercase tracking-widest text-sm mb-1">{userName}'s Cinematic Twin</p>
              <h1 className="text-4xl font-display font-bold text-white mb-1">{result.characterName}</h1>
              <p className="text-xl text-gray-300 italic">{result.movieTitle}</p>
            </div>
          </div>

          <div className="bg-dark-800/50 p-6 rounded-xl border border-dark-700 backdrop-blur-sm">
             <h3 className="text-accent-500 font-bold mb-4 flex items-center gap-2">
               <Users size={18} /> Friend Comparison
             </h3>
             <p className="text-sm text-gray-400 mb-4">
               Want to see who fits best with your personality? Share this quiz with friends and compare your "Cinematic Twin" results!
             </p>
             <Button variant="outline" fullWidth onClick={handleShare} className="text-sm">
               Share to Compare
             </Button>
          </div>
        </div>

        {/* Right Column: Report */}
        <div className="space-y-8">
          <div>
            <span className="inline-block px-3 py-1 bg-accent-900/50 text-accent-300 rounded-full text-xs font-bold tracking-wider mb-4 border border-accent-500/30">
              {result.personalityType}
            </span>
            <h2 className="text-3xl font-display font-bold text-white mb-6">Psychological Profile for {userName}</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
              <div className="bg-dark-800 p-5 rounded-lg border-l-4 border-green-500">
                <h3 className="font-bold text-green-400 mb-3 uppercase tracking-wider text-xs flex items-center gap-2">
                   <Flag size={14} className="fill-green-500" /> Green Flags
                </h3>
                <ul className="space-y-2">
                  {result.greenFlags.map((s, i) => (
                    <li key={i} className="text-gray-300 text-sm flex items-start gap-2">
                      <span className="text-green-500 mt-1">•</span> {s}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="bg-dark-800 p-5 rounded-lg border-l-4 border-red-500">
                <h3 className="font-bold text-red-400 mb-3 uppercase tracking-wider text-xs flex items-center gap-2">
                  <Flag size={14} className="fill-red-500" /> Red Flags
                </h3>
                <ul className="space-y-2">
                  {result.redFlags.map((w, i) => (
                    <li key={i} className="text-gray-300 text-sm flex items-start gap-2">
                      <span className="text-red-500 mt-1">•</span> {w}
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Food Section */}
            <div className="bg-dark-800 rounded-xl overflow-hidden border border-dark-700 mb-8 flex flex-col md:flex-row">
              <div className="md:w-1/3 relative bg-dark-900">
                {foodImageUrl ? (
                   <img src={foodImageUrl} alt={result.foodMatch} className="w-full h-full object-cover min-h-[150px]" />
                ) : (
                  <div className="w-full h-full min-h-[150px] flex items-center justify-center text-gray-600">
                    <Utensils size={32} />
                  </div>
                )}
                <div className="absolute inset-0 bg-black/20 md:hidden"></div>
              </div>
              <div className="p-5 md:w-2/3 flex flex-col justify-center">
                 <div className="flex items-center gap-2 mb-2">
                   <Utensils size={16} className="text-orange-400" />
                   <h3 className="text-xs font-bold uppercase tracking-wider text-orange-400">If you were a food...</h3>
                 </div>
                 <h4 className="text-xl font-bold text-white mb-2">{result.foodMatch}</h4>
                 <p className="text-sm text-gray-400 leading-relaxed italic">"{result.foodReason}"</p>
              </div>
            </div>

            <div className="bg-dark-800 p-5 rounded-lg border border-dark-700 mb-8">
              <div className="flex items-center gap-3 mb-4">
                <div className="bg-accent-900/50 p-2 rounded-lg text-accent-400">
                  <Briefcase size={20} />
                </div>
                <h3 className="font-bold text-white uppercase tracking-wider text-xs">Suggested Career Paths</h3>
              </div>
              <div className="space-y-4">
                {result.careerPath.map((career, idx) => (
                  <div key={idx} className="border-b border-dark-700 last:border-0 pb-3 last:pb-0">
                    <p className="text-accent-300 font-semibold text-sm mb-1">{career.role}</p>
                    <p className="text-gray-400 text-xs md:text-sm leading-snug">{career.reason}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="prose prose-invert prose-lg max-w-none">
              <h3 className="text-xl font-bold text-white border-b border-dark-700 pb-2 mb-4">Analysis Report</h3>
              <p className="text-gray-300 leading-relaxed whitespace-pre-line text-base font-light">
                {result.detailedReport}
              </p>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-4 pt-8 border-t border-dark-700">
            <Button onClick={handleDownload} variant="primary" className="flex-1 flex items-center justify-center gap-2">
              <Download size={18} /> Download Report
            </Button>
            <Button onClick={handleShare} variant="secondary" className="flex-1 flex items-center justify-center gap-2">
              <Share2 size={18} /> Share Result
            </Button>
             <Button onClick={onReset} variant="outline" className="flex-none flex items-center justify-center gap-2">
              <RefreshCw size={18} /> Retake
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};